<?php

/**
 * 全球 DNS / 名称服务器（NS）提供商识别映射
 *
 * 根据域名的 NS 主机名（如 net.dnspod.net、ns1.cloudflare.com）识别其背后的
 * DNS 托管 / 云厂商 / 注册商，返回统一的品牌名称与官网链接，便于在结果页
 * 展示"DNS 提供商"徽标并点击直达。
 *
 * 匹配策略：对 NS 主机名做小写化后，按“子串包含”匹配关键词。
 * 关键词应尽量选取 NS 主机名中稳定、唯一的片段（多为提供商主域名或专有子域）。
 * 顺序有意义：更具体 / 更易冲突的关键词应排在更靠前，命中即返回。
 */

/**
 * DNS 提供商关键词表。
 * 键：出现在 NS 主机名中的稳定子串（小写）。
 * 值：[显示名称, 官网 URL]。
 */
function dns_provider_keyword_map(): array
{
    return [
        // ===== 域名交易市场 / 停放变现平台（NS 常表明域名正在挂售或停放） =====
        'atom.com'        => ['Atom（原 Squadhelp）', 'https://www.atom.com'],
        'squadhelp'       => ['Atom（原 Squadhelp）', 'https://www.atom.com'],
        'dan.com'         => ['Dan.com（GoDaddy）', 'https://dan.com'],
        'afternic'        => ['Afternic（GoDaddy）', 'https://www.afternic.com'],
        'hugedomains'     => ['HugeDomains', 'https://www.hugedomains.com'],
        'sedo.com'        => ['Sedo', 'https://sedo.com'],
        'sedoparking'     => ['Sedo Parking', 'https://sedo.com'],
        'bodis.com'       => ['Bodis', 'https://www.bodis.com'],
        'parkingcrew'     => ['ParkingCrew', 'https://www.parkingcrew.com'],
        'above.com'       => ['Above.com', 'https://www.above.com'],
        'brandbucket'     => ['BrandBucket', 'https://www.brandbucket.com'],
        'brandpa'         => ['BrandPa', 'https://brandpa.com'],
        'efty.com'        => ['Efty', 'https://www.efty.com'],
        'dropcatch'       => ['DropCatch', 'https://www.dropcatch.com'],
        'snapnames'       => ['SnapNames', 'https://www.snapnames.com'],
        'namejet'         => ['NameJet', 'https://www.namejet.com'],
        'parklogic'       => ['Park Logic', 'https://parklogic.com'],
        'skenzo'          => ['Skenzo', 'https://www.skenzo.com'],
        'fabulous.com'    => ['Fabulous', 'https://www.fabulous.com'],
        'uniregistrymarket' => ['Uniregistry Market', 'https://uniregistry.com'],
        'buydomains'      => ['BuyDomains', 'https://www.buydomains.com'],
        'domainmarket'    => ['DomainMarket', 'https://www.domainmarket.com'],

        // ===== CDN / 全球云厂商 =====
        'ns.cloudflare'   => ['Cloudflare', 'https://www.cloudflare.com'],
        'cloudflare'      => ['Cloudflare', 'https://www.cloudflare.com'],
        'awsdns'          => ['AWS Route 53', 'https://aws.amazon.com/route53'],
        'amazonaws'       => ['AWS Route 53', 'https://aws.amazon.com/route53'],
        'azure-dns'       => ['Azure DNS', 'https://azure.microsoft.com/products/dns'],
        'azuredns'        => ['Azure DNS', 'https://azure.microsoft.com/products/dns'],
        'ns.google'       => ['Google Cloud DNS', 'https://cloud.google.com/dns'],
        'googledomains'   => ['Google Domains', 'https://domains.google'],
        'google.com'      => ['Google', 'https://domains.google'],
        'googledns'       => ['Google', 'https://cloud.google.com/dns'],
        'vercel-dns'      => ['Vercel', 'https://vercel.com'],
        'netlify'         => ['Netlify', 'https://www.netlify.com'],
        'nsone.net'       => ['NS1 (IBM)', 'https://ns1.com'],
        'nsone'           => ['NS1 (IBM)', 'https://ns1.com'],
        'ultradns'        => ['UltraDNS (Vercara)', 'https://vercara.com'],
        'akamai'          => ['Akamai', 'https://www.akamai.com'],
        'akam.net'        => ['Akamai', 'https://www.akamai.com'],
        'akadns'          => ['Akamai', 'https://www.akamai.com'],
        'edgekey'         => ['Akamai', 'https://www.akamai.com'],
        'fastly'          => ['Fastly', 'https://www.fastly.com'],
        'incapdns'        => ['Imperva (Incapsula)', 'https://www.imperva.com'],
        'impervadns'      => ['Imperva', 'https://www.imperva.com'],
        'cdn77'           => ['CDN77', 'https://www.cdn77.com'],
        'stackpath'       => ['StackPath', 'https://www.stackpath.com'],
        'gcorelabs'       => ['Gcore', 'https://gcore.com'],
        'gcore'           => ['Gcore', 'https://gcore.com'],
        'bunny'           => ['BunnyCDN', 'https://bunny.net'],
        'bunnyinfra'      => ['BunnyCDN', 'https://bunny.net'],

        // ===== 云 / VPS 主机商 =====
        'digitalocean'    => ['DigitalOcean', 'https://www.digitalocean.com'],
        'linode'          => ['Linode (Akamai)', 'https://www.linode.com'],
        'vultr'           => ['Vultr', 'https://www.vultr.com'],
        'he.net'          => ['Hurricane Electric', 'https://dns.he.net'],
        'oraclecloud'     => ['Oracle Cloud', 'https://www.oracle.com/cloud/networking/dns'],
        'oracle'          => ['Oracle Cloud', 'https://www.oracle.com/cloud/networking/dns'],
        'hetzner'         => ['Hetzner', 'https://www.hetzner.com'],
        'your-server.de'  => ['Hetzner', 'https://www.hetzner.com'],
        'ovh.net'         => ['OVHcloud', 'https://www.ovhcloud.com'],
        'ovh.ca'          => ['OVHcloud', 'https://www.ovhcloud.com'],
        'anycast.me'      => ['OVHcloud', 'https://www.ovhcloud.com'],
        'scaleway'        => ['Scaleway', 'https://www.scaleway.com'],
        'online.net'      => ['Scaleway', 'https://www.scaleway.com'],
        'contabo'         => ['Contabo', 'https://contabo.com'],
        'ionos'           => ['IONOS', 'https://www.ionos.com'],
        'ui-dns'          => ['IONOS', 'https://www.ionos.com'],
        'kasserver'       => ['All-Inkl', 'https://all-inkl.com'],
        'netcup'          => ['netcup', 'https://www.netcup.de'],
        'leaseweb'        => ['Leaseweb', 'https://www.leaseweb.com'],

        // ===== 中国厂商 =====
        'dnspod'          => ['DNSPod（腾讯云）', 'https://www.dnspod.cn'],
        'qcloud'          => ['腾讯云', 'https://cloud.tencent.com'],
        'tencent'         => ['腾讯云', 'https://cloud.tencent.com'],
        'alidns'          => ['阿里云', 'https://www.aliyun.com'],
        'aliyun'          => ['阿里云', 'https://www.aliyun.com'],
        'hichina'         => ['阿里云（万网）', 'https://wanwang.aliyun.com'],
        'dnsv'            => ['阿里云', 'https://www.aliyun.com'],
        'huaweicloud'     => ['华为云', 'https://www.huaweicloud.com'],
        'myhuaweicloud'   => ['华为云', 'https://www.huaweicloud.com'],
        'baidubce'        => ['百度智能云', 'https://cloud.baidu.com'],
        'bdydns'          => ['百度智能云', 'https://cloud.baidu.com'],
        'jdcloud'         => ['京东云', 'https://www.jdcloud.com'],
        'volcdns'         => ['火山引擎', 'https://www.volcengine.com'],
        'volcengine'      => ['火山引擎', 'https://www.volcengine.com'],
        'dnspai'          => ['帝恩思 DNSPai', 'https://www.dnspai.com'],
        'cloudxns'        => ['CloudXNS', 'https://www.cloudxns.net'],
        'dnsdun'          => ['DNSdun', 'https://www.dnsdun.com'],
        'dns.la'          => ['DNS.LA', 'https://www.dns.la'],
        '51dns'           => ['帝恩思', 'https://www.dnsla.com'],
        'ename.com'       => ['易名', 'https://www.ename.net'],
        'ename.net'       => ['易名', 'https://www.ename.net'],
        'west.cn'         => ['西部数码', 'https://www.west.cn'],
        'myhostadmin'     => ['西部数码', 'https://www.west.cn'],
        'xincache'        => ['新网', 'https://www.xinnet.com'],
        'xinnet'          => ['新网', 'https://www.xinnet.com'],
        'cnmsn'           => ['美橙互联', 'https://www.cndns.com'],
        '22.cn'           => ['爱名网', 'https://www.22.cn'],
        'sfndns'          => ['三网 DNS', 'https://www.sfn.cn'],

        // ===== 注册商 / DNS 托管 =====
        'domaincontrol'   => ['GoDaddy', 'https://www.godaddy.com'],
        'godaddy'         => ['GoDaddy', 'https://www.godaddy.com'],
        'registrar-servers' => ['Namecheap', 'https://www.namecheap.com'],
        'namecheap'       => ['Namecheap', 'https://www.namecheap.com'],
        'name-services'   => ['eNom', 'https://www.enom.com'],
        'enom'            => ['eNom', 'https://www.enom.com'],
        'dnsowl'          => ['NameSilo', 'https://www.namesilo.com'],
        'namesilo'        => ['NameSilo', 'https://www.namesilo.com'],
        'dynadot'         => ['Dynadot', 'https://www.dynadot.com'],
        'porkbun'         => ['Porkbun', 'https://porkbun.com'],
        'name.com'        => ['Name.com', 'https://www.name.com'],
        'gandi.net'       => ['Gandi', 'https://www.gandi.net'],
        'hostinger'       => ['Hostinger', 'https://www.hostinger.com'],
        'bluehost'        => ['Bluehost', 'https://www.bluehost.com'],
        'hostgator'       => ['HostGator', 'https://www.hostgator.com'],
        'siteground'      => ['SiteGround', 'https://www.siteground.com'],
        'wordpress'       => ['WordPress.com', 'https://wordpress.com/domains'],
        'wixdns'          => ['Wix', 'https://www.wix.com'],
        'squarespace'     => ['Squarespace', 'https://domains.squarespace.com'],
        'shopify'         => ['Shopify', 'https://www.shopify.com'],
        'wpengine'        => ['WP Engine', 'https://wpengine.com'],
        'flywheel'        => ['Flywheel', 'https://getflywheel.com'],
        'dreamhost'       => ['DreamHost', 'https://www.dreamhost.com'],
        'namebright'      => ['NameBright', 'https://www.namebright.com'],
        'name-servicesdns' => ['eNom', 'https://www.enom.com'],
        'domains.google'  => ['Google Domains', 'https://domains.google'],
        'spaceship'       => ['Spaceship', 'https://www.spaceship.com'],
        'dns.registrar.amazon' => ['Amazon Registrar', 'https://registrar.amazon.com'],
        'reg.ru'          => ['REG.RU', 'https://www.reg.ru'],
        'regruhosting'    => ['REG.RU', 'https://www.reg.ru'],
        'nic.ru'          => ['RU-CENTER', 'https://www.nic.ru'],
        'beget'           => ['Beget', 'https://beget.com'],
        'timeweb'         => ['Timeweb', 'https://timeweb.com'],
        'onamae'          => ['お名前.com (GMO)', 'https://www.onamae.com'],
        'gmoserver'       => ['GMO', 'https://www.gmo.jp'],
        'sakura.ne.jp'    => ['さくら (SAKURA)', 'https://www.sakura.ad.jp'],
        'value-domain'    => ['Value Domain', 'https://www.value-domain.com'],
        'gabia'           => ['Gabia', 'https://www.gabia.com'],
        'cafe24'          => ['Cafe24', 'https://www.cafe24.com'],
        'gname'           => ['Gname', 'https://www.gname.com'],
        'webnic'          => ['WebNIC', 'https://www.webnic.cc'],
        'ovhcloud'        => ['OVHcloud', 'https://www.ovhcloud.com'],
        'combell'         => ['Combell', 'https://www.combell.com'],
        'transip'         => ['TransIP', 'https://www.transip.nl'],
        'openprovider'    => ['Openprovider', 'https://www.openprovider.com'],
        'infomaniak'      => ['Infomaniak', 'https://www.infomaniak.com'],
        'loopia'          => ['Loopia', 'https://www.loopia.com'],
        'one.com'         => ['One.com', 'https://www.one.com'],
        'strato'          => ['STRATO', 'https://www.strato.de'],
        'hosteurope'      => ['Host Europe', 'https://www.hosteurope.de'],
        'domainfactory'   => ['DomainFactory', 'https://www.df.eu'],
        'inwx'            => ['INWX', 'https://www.inwx.com'],
        'core-networks'   => ['Core Networks', 'https://www.core-networks.de'],
        'schlundtech'     => ['SchlundTech', 'https://www.schlundtech.com'],
        'zone.eu'         => ['Zone', 'https://www.zone.eu'],

        // ===== 专业 DNS 服务商 =====
        'dnsmadeeasy'     => ['DNS Made Easy', 'https://dnsmadeeasy.com'],
        'easydns'         => ['easyDNS', 'https://easydns.com'],
        'zilore'          => ['Zilore', 'https://zilore.com'],
        'constellix'      => ['Constellix', 'https://constellix.com'],
        'nsproxy'         => ['NSProxy', 'https://www.nsproxy.com'],
        'clouddns'        => ['ClouDNS', 'https://www.cloudns.net'],
        'dnsimple'        => ['DNSimple', 'https://dnsimple.com'],
        'dns.he.net'      => ['Hurricane Electric', 'https://dns.he.net'],
        'rage4'           => ['Rage4 DNS', 'https://rage4.com'],
        'geoscaling'      => ['GeoScaling', 'https://www.geoscaling.com'],
        'luadns'          => ['LuaDNS', 'https://www.luadns.com'],
        'dns.com'         => ['DNS.COM', 'https://www.dns.com'],
        'p0ns'            => ['Bunny DNS', 'https://bunny.net'],
        'zoneedit'        => ['ZoneEdit', 'https://www.zoneedit.com'],
        'no-ip'           => ['No-IP', 'https://www.noip.com'],
        'dnsexit'         => ['DNSExit', 'https://www.dnsexit.com'],
        'afraid.org'      => ['FreeDNS', 'https://freedns.afraid.org'],
        'duckdns'         => ['DuckDNS', 'https://www.duckdns.org'],
        'desec.io'        => ['deSEC', 'https://desec.io'],
        'selectel'        => ['Selectel', 'https://selectel.ru'],
        'yandex'          => ['Yandex', 'https://connect.yandex.com'],
        'mail.ru'         => ['VK (Mail.ru)', 'https://hosting.vk.com'],

        // ===== 电信 / ISP / 其他区域 =====
        'worldnic'        => ['Network Solutions', 'https://www.networksolutions.com'],
        'networksolutions' => ['Network Solutions', 'https://www.networksolutions.com'],
        'register.com'    => ['Register.com', 'https://www.register.com'],
        'domainmonster'   => ['Domain Monster', 'https://www.domainmonster.com'],
        'markmonitor'     => ['MarkMonitor', 'https://www.markmonitor.com'],
        'cscdns'          => ['CSC', 'https://www.cscdbs.com'],
        'nsone.info'      => ['NS1 (IBM)', 'https://ns1.com'],
        'centralnic'      => ['CentralNic', 'https://www.centralnic.com'],
        'key-systems'     => ['Key-Systems', 'https://www.key-systems.net'],
        'rrpproxy'        => ['RRPproxy', 'https://www.rrpproxy.net'],
        'internetx'       => ['InterNetX', 'https://www.internetx.com'],
        'ascio'           => ['Ascio', 'https://www.ascio.com'],
        'nameshield'      => ['Nameshield', 'https://www.nameshield.com'],
        'eurodns'         => ['EuroDNS', 'https://www.eurodns.com'],
        'gransy'          => ['Gransy', 'https://subreg.cz'],
        'wedos'           => ['WEDOS', 'https://www.wedos.com'],
        'forpsi'          => ['FORPSI', 'https://www.forpsi.com'],
        'active24'        => ['Active 24', 'https://www.active24.com'],
        'registro.br'     => ['Registro.br', 'https://registro.br'],
        'locaweb'         => ['Locaweb', 'https://www.locaweb.com.br'],
        'uolhost'         => ['UOL Host', 'https://www.uolhost.uol.com.br'],
        'kinghost'        => ['KingHost', 'https://king.host'],
        'nic.mx'          => ['NIC México', 'https://www.nic.mx'],
        'crazydomains'    => ['Crazy Domains', 'https://www.crazydomains.com'],
        'ventraip'        => ['VentraIP', 'https://ventraip.com.au'],
        'synergywholesale' => ['Synergy Wholesale', 'https://synergywholesale.com'],
        'melbourneit'     => ['Melbourne IT', 'https://www.melbourneit.com.au'],
        'afrihost'        => ['Afrihost', 'https://www.afrihost.com'],
        'web4africa'      => ['Web4Africa', 'https://www.web4africa.com'],
        'truehost'        => ['Truehost', 'https://truehost.com'],
        'exabytes'        => ['Exabytes', 'https://www.exabytes.com'],
        'niagahoster'     => ['Niagahoster', 'https://www.niagahoster.co.id'],
        'matbao'          => ['Mắt Bão', 'https://www.matbao.net'],
        'pavietnam'       => ['PA Vietnam', 'https://www.pavietnam.vn'],
        'resellerclub'    => ['ResellerClub', 'https://www.resellerclub.com'],
        'bigrock'         => ['BigRock', 'https://www.bigrock.in'],
        'hostinger.in'    => ['Hostinger', 'https://www.hostinger.in'],

        // ============ 扩充：北美 / 全球 ============
        'domain.com'      => ['Domain.com', 'https://www.domain.com'],
        'rackspace'       => ['Rackspace', 'https://www.rackspace.com'],
        'stabletransit'   => ['Rackspace', 'https://www.rackspace.com'],
        'ibm.com'         => ['IBM Cloud', 'https://www.ibm.com/cloud'],
        'softlayer'       => ['IBM Cloud (SoftLayer)', 'https://www.ibm.com/cloud'],
        'wpengine.com'    => ['WP Engine', 'https://wpengine.com'],
        'kinsta'          => ['Kinsta', 'https://kinsta.com'],
        'pantheon'        => ['Pantheon', 'https://pantheon.io'],
        'render.com'      => ['Render', 'https://render.com'],
        'fly.dev'         => ['Fly.io', 'https://fly.io'],
        'railway'         => ['Railway', 'https://railway.app'],
        'heroku'          => ['Heroku', 'https://www.heroku.com'],
        'github.io'       => ['GitHub Pages', 'https://pages.github.com'],
        'githubusercontent' => ['GitHub', 'https://github.com'],
        'gitlab'          => ['GitLab Pages', 'https://gitlab.com'],
        'cloudns.net'     => ['ClouDNS', 'https://www.cloudns.net'],
        'nsservice'       => ['1&1 IONOS', 'https://www.ionos.com'],
        'a2hosting'       => ['A2 Hosting', 'https://www.a2hosting.com'],
        'inmotionhosting' => ['InMotion Hosting', 'https://www.inmotionhosting.com'],
        'greengeeks'      => ['GreenGeeks', 'https://www.greengeeks.com'],
        'nexcess'         => ['Nexcess', 'https://www.nexcess.net'],
        'liquidweb'       => ['Liquid Web', 'https://www.liquidweb.com'],
        'cloudways'       => ['Cloudways', 'https://www.cloudways.com'],
        'hostwinds'       => ['Hostwinds', 'https://www.hostwinds.com'],
        'ipage'           => ['iPage', 'https://www.ipage.com'],
        'fatcow'          => ['FatCow', 'https://www.fatcow.com'],
        'justhost'        => ['JustHost', 'https://www.justhost.com'],
        'namehero'        => ['NameHero', 'https://www.namehero.com'],
        'chemicloud'      => ['ChemiCloud', 'https://chemicloud.com'],
        'scala'           => ['ScalaHosting', 'https://www.scalahosting.com'],
        'krystal'         => ['Krystal', 'https://krystal.io'],

        // ============ 扩充：加拿大 ============
        'hostpapa'        => ['HostPapa', 'https://www.hostpapa.com'],
        'webhostingcanada' => ['Web Hosting Canada', 'https://whc.ca'],
        'ca.inc'          => ['CIRA', 'https://www.cira.ca'],

        // ============ 扩充：英国 / 爱尔兰 ============
        '123-reg'         => ['123 Reg', 'https://www.123-reg.co.uk'],
        '123reg'          => ['123 Reg', 'https://www.123-reg.co.uk'],
        'fasthosts'       => ['Fasthosts', 'https://www.fasthosts.co.uk'],
        'heartinternet'   => ['Heart Internet', 'https://www.heartinternet.uk'],
        'names.co.uk'     => ['Names.co.uk', 'https://www.names.co.uk'],
        'tsohost'         => ['TSOHost', 'https://www.tsohost.com'],
        '20i.com'         => ['20i', 'https://www.20i.com'],
        'kualo'           => ['Kualo', 'https://www.kualo.com'],
        'blacknight'      => ['Blacknight', 'https://www.blacknight.com'],
        'nominet'         => ['Nominet', 'https://www.nominet.uk'],

        // ============ 扩充：德语区 ============
        'server4you'      => ['Server4You', 'https://www.server4you.de'],
        'goneo'           => ['goneo', 'https://www.goneo.de'],
        'variomedia'      => ['Variomedia', 'https://www.variomedia.de'],
        'hosttech'        => ['hosttech', 'https://www.hosttech.eu'],
        'cyon'            => ['cyon', 'https://www.cyon.ch'],
        'hostpoint'       => ['Hostpoint', 'https://www.hostpoint.ch'],
        'metanet'         => ['Metanet', 'https://www.metanet.ch'],
        'nine.ch'         => ['nine', 'https://nine.ch'],
        'edis'            => ['EDIS', 'https://www.edis.at'],
        'world4you'       => ['World4You', 'https://www.world4you.com'],
        'easyname'        => ['easyname', 'https://www.easyname.com'],

        // ============ 扩充：法国 / 比荷卢 ============
        'o2switch'        => ['o2switch', 'https://www.o2switch.fr'],
        'planethoster'    => ['PlanetHoster', 'https://www.planethoster.com'],
        'ikoula'          => ['Ikoula', 'https://www.ikoula.com'],
        'lws.fr'          => ['LWS', 'https://www.lws.fr'],
        'amenworld'       => ['Amen', 'https://www.amen.fr'],
        'versio'          => ['Versio', 'https://www.versio.nl'],
        'antagonist'      => ['Antagonist', 'https://www.antagonist.nl'],
        'vimexx'          => ['Vimexx', 'https://www.vimexx.nl'],
        'hostnet'         => ['Hostnet', 'https://www.hostnet.nl'],
        'mijndomein'      => ['Mijndomein', 'https://www.mijndomein.nl'],
        'argeweb'         => ['Argeweb', 'https://www.argeweb.nl'],
        'flexwebhosting'  => ['Flexwebhosting', 'https://www.flexwebhosting.nl'],

        // ============ 扩充：南欧（意 / 西 / 葡 / 希） ============
        'aruba.it'        => ['Aruba', 'https://www.aruba.it'],
        'register.it'     => ['Register.it', 'https://www.register.it'],
        'netsons'         => ['Netsons', 'https://www.netsons.com'],
        'seeweb'          => ['Seeweb', 'https://www.seeweb.it'],
        'keliweb'         => ['Keliweb', 'https://www.keliweb.it'],
        'dondominio'      => ['DonDominio', 'https://www.dondominio.com'],
        'cdmon'           => ['CDmon', 'https://www.cdmon.com'],
        'arsys'           => ['Arsys', 'https://www.arsys.es'],
        'dinahosting'     => ['DinaHosting', 'https://dinahosting.com'],
        'raiolanetworks'  => ['Raiola Networks', 'https://raiolanetworks.es'],
        'ptisp'           => ['PTISP', 'https://www.ptisp.pt'],
        'amentio'         => ['Amen.pt', 'https://www.amen.pt'],
        'papaki'          => ['Papaki', 'https://www.papaki.com'],
        'pointerhq'       => ['Pointer', 'https://www.pointer.gr'],
        'top.host'        => ['top.host', 'https://top.host'],

        // ============ 扩充：北欧 ============
        'binero'          => ['Binero', 'https://www.binero.se'],
        'oderland'        => ['Oderland', 'https://www.oderland.se'],
        'glesys'          => ['GleSYS', 'https://glesys.com'],
        'domeneshop'      => ['Domeneshop', 'https://domene.shop'],
        'curanet'         => ['Curanet', 'https://curanet.dk'],
        'gratisdns'       => ['GratisDNS', 'https://gratisdns.dk'],
        'simply.com'      => ['Simply.com', 'https://www.simply.com'],
        'louhi'           => ['Louhi', 'https://louhi.fi'],
        'shellit'         => ['Shellit', 'https://www.shellit.se'],

        // ============ 扩充：中东欧 / 独联体 ============
        'webglobe'        => ['WebGlobe', 'https://www.webglobe.sk'],
        'websupport'      => ['WebSupport', 'https://www.websupport.sk'],
        'ignum'           => ['Ignum', 'https://www.ignum.cz'],
        'thecamels'       => ['The Camels', 'https://thecamels.org'],
        'cyberfolks'      => ['cyber_Folks', 'https://cyberfolks.pl'],
        'zenbox'          => ['Zenbox', 'https://zenbox.pl'],
        'home.pl'         => ['home.pl', 'https://home.pl'],
        'nazwa.pl'        => ['nazwa.pl', 'https://www.nazwa.pl'],
        'dhosting'        => ['dhosting', 'https://dhosting.pl'],
        'sprinthost'      => ['SprintHost', 'https://sprinthost.ru'],
        'mchost'          => ['McHost', 'https://mchost.ru'],
        'jino.ru'         => ['Jino', 'https://jino.ru'],
        'fozzy'           => ['Fozzy', 'https://fozzy.com'],
        'ukraine.com.ua'  => ['Ukraine.com.ua', 'https://www.ukraine.com.ua'],
        'hostpro'         => ['HostPro', 'https://hostpro.ua'],
        'imena'           => ['Imena', 'https://www.imena.ua'],

        // ============ 扩充：中东 ============
        'aeserver'        => ['AEserver', 'https://aeserver.com'],
        'tasjeel'         => ['Tasjeel.ae', 'https://tasjeel.ae'],
        'buzinessware'    => ['Buzinessware', 'https://www.buzinessware.com'],
        'nasserver'       => ['nasserver', 'https://www.ns.co.il'],
        'domainthenet'    => ['Domain The Net', 'https://www.domainthenet.com'],
        'livedns'         => ['LiveDNS', 'https://www.livedns.co.il'],
        'saudi.net.sa'    => ['STC', 'https://www.stc.com.sa'],
        'atlas.net.sa'    => ['Atlas Store', 'https://atlas.sa'],

        // ============ 扩充：东亚（中国大陆） ============
        'now.cn'          => ['时代互联', 'https://www.now.cn'],
        '35dns'           => ['三五互联', 'https://www.35.com'],
        '35.com'          => ['三五互联', 'https://www.35.com'],
        'zzidc'           => ['景安网络', 'https://www.zzidc.com'],
        'zzy.cn'          => ['中资源', 'https://www.zzy.cn'],
        '4.cn'            => ['4.cn', 'https://www.4.cn'],
        'juming'          => ['聚名网', 'https://www.juming.com'],
        'nicenic'         => ['NiceNIC', 'https://www.nicenic.net'],
        'quyu'            => ['趣域', 'https://www.quyu.net'],
        'zhujiwu'         => ['景安主机屋', 'https://www.zhujiwu.com'],
        'ucloud'          => ['UCloud', 'https://www.ucloud.cn'],
        'qingcloud'       => ['青云 QingCloud', 'https://www.qingcloud.com'],
        'ksyun'           => ['金山云', 'https://www.ksyun.com'],
        'chinanetcenter'  => ['网宿科技', 'https://www.wangsu.com'],
        'wscdns'          => ['网宿科技', 'https://www.wangsu.com'],
        'kingsoft'        => ['金山云', 'https://www.ksyun.com'],

        // ============ 扩充：东亚（日 / 韩 / 台 / 港） ============
        'conoha'          => ['ConoHa (GMO)', 'https://www.conoha.jp'],
        'xserver'         => ['Xserver', 'https://www.xserver.ne.jp'],
        'xdomain'         => ['Xserver Domain', 'https://www.xdomain.ne.jp'],
        'lolipop'         => ['ロリポップ (GMO)', 'https://lolipop.jp'],
        'muumuu'          => ['ムームードメイン (GMO)', 'https://muumuu-domain.com'],
        'kagoya'          => ['KAGOYA', 'https://www.kagoya.jp'],
        'sakura.ad.jp'    => ['さくら (SAKURA)', 'https://www.sakura.ad.jp'],
        'star-domain'     => ['スタードメイン', 'https://www.star-domain.jp'],
        'muumuu-domain'   => ['ムームードメイン', 'https://muumuu-domain.com'],
        'megazone'        => ['MegaZone (hosting.kr)', 'https://www.hosting.kr'],
        'dotname'         => ['Dotname Korea', 'https://www.dotname.co.kr'],
        'gabia.co.kr'     => ['Gabia', 'https://www.gabia.com'],
        'hinet'           => ['HiNet 中華電信', 'https://domain.hinet.net'],
        'seed.net.tw'     => ['SEEDNet', 'https://domain.seed.net.tw'],
        'net-chinese'     => ['網路中文 Net-Chinese', 'https://www.net-chinese.com.tw'],
        'pchome'          => ['PChome', 'https://myname.pchome.com.tw'],
        'hkdnr'           => ['HKDNR', 'https://www.hkdnr.hk'],

        // ============ 扩充：东南亚 ============
        'rumahweb'        => ['Rumahweb', 'https://www.rumahweb.com'],
        'idwebhost'       => ['IDwebhost', 'https://idwebhost.com'],
        'qwords'          => ['Qwords', 'https://www.qwords.com'],
        'dewaweb'         => ['Dewaweb', 'https://www.dewaweb.com'],
        'domainesia'      => ['DomaiNesia', 'https://www.domainesia.com'],
        'ipserverone'     => ['IP ServerOne', 'https://www.ipserverone.com'],
        'shinjiru'        => ['Shinjiru', 'https://www.shinjiru.com.my'],
        'serverfreak'     => ['ServerFreak', 'https://www.serverfreak.com'],
        'vodien'          => ['Vodien', 'https://www.vodien.com'],
        'signetique'      => ['Signetique', 'https://www.signetique.com'],
        'vinahost'        => ['VinaHost', 'https://www.vinahost.vn'],
        'tenten'          => ['TENTEN', 'https://tenten.vn'],
        'bkns'            => ['BKNS', 'https://www.bkns.vn'],
        'nhanhoa'         => ['Nhân Hòa', 'https://nhanhoa.com'],
        'inet.vn'         => ['iNET', 'https://inet.vn'],

        // ============ 扩充：南亚 ============
        'milesweb'        => ['MilesWeb', 'https://www.milesweb.com'],
        'hostingraja'     => ['HostingRaja', 'https://www.hostingraja.in'],
        'znetlive'        => ['ZNetLive', 'https://www.znetlive.com'],
        'net4india'       => ['Net4', 'https://www.net4.in'],
        'hostkarle'       => ['HostKarle', 'https://hostkarle.in'],
        'bodhost'         => ['BodHOST', 'https://www.bodhost.com'],
        'exonhost'        => ['ExonHost', 'https://exonhost.com'],
        'hostever'        => ['Hostever', 'https://hostever.com'],

        // ============ 扩充：非洲 ============
        'webafrica'       => ['Web Africa', 'https://www.webafrica.com'],
        'hostafrica'      => ['HOSTAFRICA', 'https://www.hostafrica.com'],
        '1-grid'          => ['1-grid', 'https://www.1-grid.com'],
        'domains.co.za'   => ['Domains.co.za', 'https://domains.co.za'],
        'axxess'          => ['Axxess', 'https://www.axxess.co.za'],
        'gridhost'        => ['Gridhost', 'https://www.gridhost.co.za'],
        'diadem'          => ['Diadem', 'https://www.diadem.co.za'],
        'whogohost'       => ['WhoGoHost', 'https://www.whogohost.com'],
        'smartweb'        => ['SmartWeb', 'https://www.smartweb.com.ng'],
        'garanntor'       => ['Garanntor', 'https://www.garanntor.com'],
        'qservers'        => ['Qservers', 'https://www.qservers.net'],
        'sasahost'        => ['Sasahost', 'https://sasahost.co.ke'],
        'hostpinnacle'    => ['HostPinnacle', 'https://www.hostpinnacle.co.ke'],
        'safaricom'       => ['Safaricom', 'https://www.safaricom.co.ke'],
        'menara'          => ['Menara', 'https://www.menara.ma'],
        'egyptnetwork'    => ['Egypt Network', 'https://www.egyptnetwork.com'],

        // ============ 扩充：拉丁美洲 ============
        'hostgator.com.br' => ['HostGator Brasil', 'https://www.hostgator.com.br'],
        'hostnet.com.br'  => ['Hostnet', 'https://www.hostnet.com.br'],
        'valuehost'       => ['ValueHost', 'https://www.valuehost.com.br'],
        'redehost'        => ['RedeHost', 'https://www.redehost.com.br'],
        'ferozo'          => ['Ferozo', 'https://www.ferozo.com'],
        'dattatec'        => ['DonWeb / Dattatec', 'https://www.dattatec.com'],
        'neubox'          => ['Neubox', 'https://www.neubox.com'],
        'akky'            => ['Akky', 'https://www.akky.mx'],
        'haulmer'         => ['Haulmer', 'https://www.haulmer.com'],
        'hostname.cl'     => ['HostName Chile', 'https://www.hostname.cl'],
        'colombiahosting' => ['Colombia Hosting', 'https://www.colombiahosting.com.co'],
        'cointernet'      => ['.CO Internet', 'https://www.cointernet.com.co'],
        'planetahosting'  => ['Planeta Hosting', 'https://www.planetahosting.com.ar'],

        // ============ 扩充：大洋洲 ============
        'webcentral'      => ['Webcentral', 'https://www.webcentral.au'],
        'micron21'        => ['Micron21', 'https://www.micron21.com'],
        'conetix'         => ['Conetix', 'https://www.conetix.com.au'],
        'panthur'         => ['Panthur', 'https://www.panthur.com.au'],
        'zuver'           => ['Zuver', 'https://www.zuver.net.au'],
        'digitalpacific'  => ['Digital Pacific', 'https://www.digitalpacific.com.au'],
        'sitehost.nz'     => ['SiteHost', 'https://www.sitehost.nz'],
        'umbrellar'       => ['Umbrellar', 'https://umbrellar.com'],
        'iwantmyname'     => ['iwantmyname', 'https://iwantmyname.com'],
        'freeparking.co.nz' => ['Freeparking', 'https://www.freeparking.co.nz'],
        'metaname'        => ['Metaname', 'https://www.metaname.net'],

        // ============ 扩充：批发 / 品牌保护 / 平台 ============
        'publicdomainregistry' => ['PDR (Endurance)', 'https://publicdomainregistry.com'],
        'registrar-servers2' => ['Namecheap', 'https://www.namecheap.com'],
        'secureserver'    => ['GoDaddy (SecureServer)', 'https://www.godaddy.com'],
        'wildwestdomains' => ['Wild West Domains (GoDaddy)', 'https://www.wildwestdomains.com'],
        'onlinenic'       => ['OnlineNIC', 'https://www.onlinenic.com'],
        'eranet'          => ['Eranet', 'https://www.eranet.com'],
        '1api'            => ['1API (Hexonet)', 'https://www.1api.net'],
        'hexonet'         => ['Hexonet', 'https://www.hexonet.net'],
        'realtimeregister' => ['Realtime Register', 'https://www.realtimeregister.com'],
        'nameisp'         => ['NameISP', 'https://www.nameisp.com'],
        'ports.group'     => ['Ports Group', 'https://portsgroup.com'],
        'abion'           => ['Abion', 'https://www.abion.com'],
        'safenames'       => ['SafeNames', 'https://www.safenames.net'],
        'comlaude'        => ['Com Laude', 'https://comlaude.com'],
        'brandsight'      => ['Brandsight', 'https://www.brandsight.com'],
        'identity.digital' => ['Identity Digital', 'https://www.identity.digital'],
        'donuts'          => ['Identity Digital (Donuts)', 'https://www.identity.digital'],
        'radix'           => ['Radix', 'https://radix.website'],
        'nic.google'      => ['Google Registry', 'https://www.registry.google'],
    ];
}

/**
 * 根据单个 NS 主机名识别 DNS 提供商。
 * 返回 ['name' => 显示名, 'url' => 官网]，无法识别时返回 ['name' => '', 'url' => '']。
 */
function dns_provider_detect(string $nameserver): array
{
    $n = strtolower(trim($nameserver));
    if ($n === '') {
        return ['name' => '', 'url' => ''];
    }
    foreach (dns_provider_keyword_map() as $kw => $info) {
        if (strpos($n, $kw) !== false) {
            return ['name' => $info[0], 'url' => $info[1]];
        }
    }
    return ['name' => '', 'url' => ''];
}
