<?php

// 全面的状态码到中文映射，涵盖 EPP 标准、gTLD 和 ccTLD 状态
// 从 index.php 抽离，返回数组供模板使用

return [
      // EPP 标准状态 (IANA 定义)
      'active' => '活跃',
      'inactive' => '未激活',
      'pendingCreate' => '待创建',
      'pendingTransfer' => '待转移',
      'pendingUpdate' => '待更新',
      'pendingRenew' => '待续费',
      'pendingDelete' => '待删除',
      'pendingRelease' => '待释放',
      'pendingRestore' => '待恢复',
      'pendingCancel' => '待取消',
      'pendingValidation' => '待验证',
      'clientHold' => '客户暂停',
      'serverHold' => '服务器暂停',
      'clientUpdateProhibited' => '禁止客户更新',
      'serverUpdateProhibited' => '禁止服务器更新',
      'clientTransferProhibited' => '禁止客户转移',
      'serverTransferProhibited' => '禁止服务器转移',
      'clientDeleteProhibited' => '禁止客户删除',
      'serverDeleteProhibited' => '禁止服务器删除',
      'clientCreateProhibited' => '禁止客户创建',
      'serverCreateProhibited' => '禁止服务器创建',
      'clientRenewProhibited' => '禁止客户续费',
      'serverRenewProhibited' => '禁止服务器续费',
      'autoRenew' => '自动续费',
      'autoRenewPeriod' => '自动续费期',
      'renewPeriod' => '续费期',
      'transferPeriod' => '转移宽限期',
      'addPeriod' => '添加宽限期',
      'redemptionPeriod' => '赎回期',
      'pendingDeleteScheduled' => '待删除（已计划）',
      'pendingTransferScheduled' => '待转移（已计划）',
      'pendingRestoreScheduled' => '待恢复（已计划）',
      'restorePeriod' => '恢复期',
      'gracePeriod' => '宽限期',
      'ok' => '正常',
      'linked' => '已链接',
      'associated' => '已关联',
      'expired' => '已过期',
      'inRedemption' => '赎回中',
      'serverObsolete' => '服务器过时',
      'clientObsolete' => '客户过时',

      // gTLD 特定状态 (如 .com, .org, .net)
      'premium' => '溢价域名',
      'pendingAuction' => '待拍卖',
      'auctionHeld' => '拍卖完成',
      'pendingReleaseToAuction' => '待释放至拍卖',
      'registryReserved' => '注册局保留',
      'sunrise' => '日出期',
      'landrush' => '抢注期',
      'premiumRenewPeriod' => '溢价续费期',
      'pendingSunrise' => '待日出期',
      'pendingLandrush' => '待抢注期',

      // ccTLD 特定状态
      // .uk (Nominet)
      'RegistryLock' => '注册局锁定（.uk）',
      'RegistryHold' => '注册局暂停（.uk）',
      'Quarantine' => '隔离状态（.uk）',
      'PendingUpdateNominet' => '待更新（.uk）',
      'RegistrantHold' => '注册人暂停（.uk）',
      // .de (DENIC)
      'NserverChangePending' => '名称服务器更改待处理（.de）',
      'DeleteCandidate' => '删除候选（.de）',
      'LockedDE' => '已锁定（.de）',
      'PendingDeleteDE' => '待删除（.de）',
      // .ro (ROTLD)
      'DeleteProhibited' => '禁止删除（.ro）',
      'RegistrantTransferProhibited' => '注册人转移禁止（.ro）',
      'RegistrantUpdateProhibited' => '注册人更新禁止（.ro）',
      'RegistrantDeleteProhibited' => '注册人删除禁止（.ro）',
      'LockedRO' => '已锁定（.ro）',
      'PendingUpdateROTLD' => '待更新（.ro）',
      'PendingRenewalRO' => '待续费（.ro）',
      // .cn (CNNIC)
      'serverPendingTransfer' => '服务器待转移（.cn）',
      'clientPendingTransfer' => '客户待转移（.cn）',
      'PendingVerificationCNNIC' => '待验证（.cn）',
      'SuspendedCN' => '已暂停（.cn）',
      'RegistryLockCN' => '注册局锁定（.cn）',
      'PendingDeleteCN' => '待删除（.cn）',
      // .fr (AFNIC)
      'pendingValidationFR' => '待验证（.fr）',
      'onHoldFR' => '暂停状态（.fr）',
      'LockedFR' => '已锁定（.fr）',
      'PendingUpdateFR' => '待更新（.fr）',
      // .jp (JPRS)
      'pendingRegistrationJP' => '待注册（.jp）',
      'temporaryHold' => '临时暂停（.jp）',
      'LockedJP' => '已锁定（.jp）',
      'PendingTransferJP' => '待转移（.jp）',
      // .au (auDA)
      'ServerRenewProhibitedAU' => '禁止服务器续费（.au）',
      'ClientUpdateProhibitedAU' => '禁止客户更新（.au）',
      'PendingRenewalAU' => '待续费（.au）',
      // .nl (SIDN)
      'PendingValidationNL' => '待验证（.nl）',
      'LockedNL' => '已锁定（.nl）',
      'QuarantineNL' => '隔离状态（.nl）',
      // 其他通用 ccTLD 状态
      'Suspended' => '已暂停',
      'Hold' => '持有状态',
      'Released' => '已释放',
      'PendingCancellation' => '待取消',
      'registrantHold' => '注册人持有',
      'serverLock' => '服务器锁定',
      'clientLock' => '客户锁定',
      'pendingReleaseToRegistry' => '待释放至注册局',
      'pendingRegistryApproval' => '待注册局批准',
      'pendingDispute' => '待争议解决',
      'fraudHold' => '欺诈暂停',
];
